2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Configure stats pid to 33069
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Loading settings from /Users/ujjwalsingh/.config/wandb/settings
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Loading settings from /Users/ujjwalsingh/Development/dl/DA6401/wandb/settings
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run.py', 'program_abspath': '/Users/ujjwalsingh/Development/dl/DA6401/run.py', 'program': '/Users/ujjwalsingh/Development/dl/DA6401/run.py'}
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-17 23:31:17,989 INFO    MainThread:33069 [wandb_init.py:_log_setup():527] Logging user logs to /Users/ujjwalsingh/Development/dl/DA6401/wandb/run-20250317_233117-k5cnx9x0/logs/debug.log
2025-03-17 23:31:17,990 INFO    MainThread:33069 [wandb_init.py:_log_setup():528] Logging internal logs to /Users/ujjwalsingh/Development/dl/DA6401/wandb/run-20250317_233117-k5cnx9x0/logs/debug-internal.log
2025-03-17 23:31:17,990 INFO    MainThread:33069 [wandb_init.py:init():567] calling init triggers
2025-03-17 23:31:17,990 INFO    MainThread:33069 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2025-03-17 23:31:17,990 INFO    MainThread:33069 [wandb_init.py:init():617] starting backend
2025-03-17 23:31:17,990 INFO    MainThread:33069 [wandb_init.py:init():621] setting up manager
2025-03-17 23:31:17,992 INFO    MainThread:33069 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-17 23:31:17,994 INFO    MainThread:33069 [wandb_init.py:init():629] backend started and connected
2025-03-17 23:31:17,998 INFO    MainThread:33069 [wandb_init.py:init():721] updated telemetry
2025-03-17 23:31:18,018 INFO    MainThread:33069 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2025-03-17 23:31:19,218 ERROR   MainThread:33069 [wandb_init.py:init():780] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-03-17 23:31:19,522 ERROR   MainThread:33069 [wandb_init.py:init():1205] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/Users/ujjwalsingh/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1187, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/ujjwalsingh/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 786, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-03-17 23:31:20,533 WARNING MsgRouterThr:33069 [router.py:message_loop():77] message_loop has been closed
